(function(){'use strict';
const A=window.KQV4AdminProduct={};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return Number(n||0).toLocaleString('id-ID')}
function col(){const s=window.KQV4AdminState;return window.KQV4.FirestoreAdapter.collection('produk',s.tokoId,new Set(['produk']))}
function state(){return window.KQV4AdminState}
function modal(){return document.getElementById('productModal')}
A.open=function(id){const s=state(), p=id?s.products.find(x=>x.id===id):null; if(id&&!p)return;
 let m=modal(); if(!m){m=document.createElement('div');m.id='productModal';m.className='modal-backdrop';document.body.appendChild(m)}
 m.innerHTML=`<div class="modal-card"><div class="modal-head"><div><b>${p?'Edit Produk':'Tambah Produk'}</b><small>${p?'Perbarui data katalog':'Masukkan produk ke katalog toko'}</small></div><button class="icon-btn" data-pact="close">×</button></div><form id="productForm"><div class="form-grid"><label>Kode / ID<input name="id" value="${esc(p?.id||('BRG-'+Date.now()))}" ${p?'readonly':''} required></label><label>Barcode<input name="barcode" value="${esc(p?.barcode||'')}"></label><label class="full">Nama Produk<input name="nama" value="${esc(p?.nama||'')}" required></label><label>Kategori<input name="kategori" value="${esc(Array.isArray(p?.kategori)?p.kategori.join(', '):(p?.kategori||'Umum'))}"></label><label>Satuan<select name="satuan"><option ${p?.satuan==='pcs'?'selected':''}>pcs</option><option ${p?.satuan==='rtg'?'selected':''}>rtg</option><option ${p?.satuan==='kg'?'selected':''}>kg</option><option ${p?.satuan==='liter'?'selected':''}>liter</option></select></label><label>Isi / RTG<input name="isiRtg" type="number" min="1" step="1" value="${Number(p?.isiRtg||10)}"></label><label>Stok<input name="stok" type="number" min="0" step="0.001" value="${Number(p?.stok||0)}"></label><label>Modal<input name="modal" type="number" min="0" step="1" value="${Number(p?.modal||0)}"></label><label>Harga Jual<input name="harga" type="number" min="0" step="1" value="${Number(p?.harga||0)}"></label><label class="full">URL Foto<input name="foto" value="${esc(p?.foto||'')}" placeholder="https://..."></label></div><div class="modal-actions"><button type="button" class="btn" data-pact="close">Batal</button>${p?'<button type="button" class="btn danger" data-pact="delete">Hapus</button>':''}<button class="btn primary" type="submit">${p?'Simpan Perubahan':'Tambah Produk'}</button></div></form></div>`;
 m.classList.add('show');
 m.querySelectorAll('[data-pact="close"]').forEach(x=>x.onclick=()=>m.remove());
 const del=m.querySelector('[data-pact="delete"]'); if(del)del.onclick=async()=>{if(!confirm('Hapus produk ini dari toko?'))return;try{await col().doc(p.id).delete();m.remove();window.KQV4AdminRender();}catch(e){console.error(e);alert('Gagal menghapus: '+e.message)}};
 m.querySelector('#productForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget), id=String(f.get('id')).trim(), nama=String(f.get('nama')).trim();if(!id||!nama)return alert('Kode dan nama produk wajib diisi.');const satuan=String(f.get('satuan')||'pcs').toLowerCase(), isi=Math.max(1,Number(f.get('isiRtg'))||10), stok=Math.max(0,Number(f.get('stok'))||0), modal=Number(f.get('modal'))||0, harga=Number(f.get('harga'))||0, kategori=String(f.get('kategori')||'Umum').split(',').map(x=>x.trim()).filter(Boolean);const data={nama,barcode:String(f.get('barcode')||'').trim(),kategori,satuan,isiRtg:isi,stok,modal,harga,modalRtg:modal*isi,hargaRtg:harga*isi,foto:String(f.get('foto')||'').trim()};try{await col().doc(id).set(data,{merge:true});m.remove();window.KQV4AdminRender();}catch(e){console.error(e);alert('Gagal menyimpan: '+e.message)}};
};
A.restock=async function(id){const s=state(),p=s.products.find(x=>x.id===id);if(!p)return;const q=prompt('Jumlah stok yang ditambahkan untuk '+p.nama, '10');if(q===null)return;const qty=Number(q);if(!Number.isFinite(qty)||qty<=0)return alert('Jumlah tidak valid.');try{await col().doc(id).update({stok:Number(p.stok||0)+qty});window.KQV4AdminRender();}catch(e){console.error(e);alert('Gagal restock: '+e.message)}};
})();
