(function(){'use strict';
const SCOPED=new Set(['produk','pelanggan','transaksi','catatan','db_chat_rumpi','chats','pengaturan']);
let chatUnsub=null, orderUnsub=null, loginReturn='home';
const DEFAULT_TOKO='toko_v13'; const urlToko=new URLSearchParams(location.search).get('toko'); let tokoId=(urlToko&&/^[A-Za-z0-9_-]+$/.test(urlToko)?urlToko:DEFAULT_TOKO), products=[], category='Semua', selected=null, detailQty=1, payment='Tunai', unsub=[];
const $=id=>document.getElementById(id), money=v=>'Rp '+Number(v||0).toLocaleString('id-ID');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const col=name=>window.KQV4.FirestoreAdapter.collection(name,tokoId,SCOPED); const photo=p=>p?.foto||p?.fotoUrl||p?.image||p?.gambar||'';
const cartKey=()=>`kqv4_cart_${String(tokoId||DEFAULT_TOKO)}_${String(localStorage.getItem('cust_phone_v4')||'guest').replace(/[^a-zA-Z0-9_-]/g,'_')}`; const cart=()=>JSON.parse(localStorage.getItem(cartKey())||'[]'); const saveCart=c=>localStorage.setItem(cartKey(),JSON.stringify(c));
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,2300)}
function card(p){const id=p.code||p.id,src=photo(p);return `<article class="product" data-product="${esc(id)}"><div class="photo">${src?`<img src="${esc(src)}" alt="${esc(p.nama||'Produk')}" loading="lazy">`:'🛒'}</div><b>${esc(p.nama||'Produk')}</b><small>${money(p.hargaJual??p.harga)}</small><button type="button" data-add="${esc(id)}">+</button></article>`}
function mini(p){const src=photo(p);return `<article data-product="${esc(p.code||p.id)}"><div class="mini-photo">${src?`<img src="${esc(src)}" alt="${esc(p.nama||'Produk')}" loading="lazy">`:'🛒'}</div><b>${esc(p.nama||'Produk')}</b><small>${money(p.hargaJual??p.harga)}</small></article>`}
function render(list,id,limit){const a=limit?list.slice(0,limit):list;$(id).innerHTML=a.length?a.map(card).join(''):'<div class="empty">Belum ada produk.</div>';bindProductClicks()}
function renderMini(list,id){$(id).innerHTML=list.length?list.slice(0,3).map(mini).join(''):'<div class="empty">Belum ada data.</div>';bindProductClicks()}
function add(p,qty=1){const c=cart(),id=String(p.id||p.code||''),h=c.find(x=>String(x.id||x.code)===id);if(h)h.qty+=qty;else c.push({id,code:id,nama:p.nama,harga:Number(p.hargaJual??p.harga??0),qty});saveCart(c);updateCartBadge();toast(`${p.nama} masuk keranjang 🛒`)}
function bindProductClicks(){document.querySelectorAll('[data-product]').forEach(el=>el.onclick=e=>{const p=products.find(x=>(x.code||x.id)==el.dataset.product);if(!p)return;if(e.target.closest('[data-add]')){e.stopPropagation();add(p);return}openDetail(p)})}
function renderHome(){render(products.slice(-8).reverse(),'latest-products',4);render(products.slice(0,4),'trending-products',4);renderMini(products,'stock-products');renderMini(products.slice().reverse(),'recipe-products');}
function categories(){const cats=[...new Set(products.map(p=>p.kategori||p.category).filter(Boolean))];$('category-chips').innerHTML=['Semua',...cats].map(c=>`<button class="${c===category?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;categories();renderCatalog()})}
function renderCatalog(){const list=category==='Semua'?products:products.filter(p=>String(p.kategori||p.category||'').toLowerCase()===category.toLowerCase());render(list,'catalog-products')}
function search(q){const term=q.trim().toLowerCase();$('search-clear').hidden=!term;if(!term){$('search-panel').hidden=true;return}const f=products.filter(p=>`${p.nama||''} ${p.kategori||p.category||''} ${p.deskripsi||''}`.toLowerCase().includes(term));$('search-panel').hidden=false;$('result-count').textContent=`${f.length} produk`;render(f,'search-products')}
function show(tab){['home-content','catalog-screen','cart-screen','checkout-screen','chat-screen','profile-screen'].forEach(id=>$(id).hidden=true);const map={home:'home-content',catalog:'catalog-screen',cart:'cart-screen',checkout:'checkout-screen',chat:'chat-screen',profile:'profile-screen'};$(map[tab]||'home-content').hidden=false;document.querySelectorAll('#bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='catalog'){categories();renderCatalog()}if(tab==='cart')renderCart();if(tab==='checkout')renderCheckout();if(tab==='profile')renderProfile();if(tab==='chat')listenCustomerChat();if(tab==='profile')listenCustomerOrders()}
function openLogin(returnTab){loginReturn=returnTab||'home';$('login-screen').hidden=false;document.body.classList.add('login-open');setTimeout(()=>$('login-phone').focus(),30)}
function closeLogin(){ $('login-screen').hidden=true; document.body.classList.remove('login-open') }
function greeting(){const h=new Date().getHours();$('greeting').innerHTML=`${h<11?'Selamat pagi 👋':h<15?'Selamat siang ☀️':h<18?'Selamat sore 🌤️':'Selamat malam 🌙'}<br><small>Semoga harimu menyenangkan!</small>`}
async function loadStore(){try{const s=await col('pengaturan').doc('toko_v13').get();if(s.exists){const d=s.data();$('store-name').textContent=d.nama||d.namaToko||'Warung Sederhana'}}catch(e){console.warn(e)}}
function listen(){unsub.forEach(f=>f&&f());unsub=[];unsub.push(col('produk').onSnapshot(s=>{products=s.docs.map(d=>({...d.data(),id:d.id,code:d.id,legacyCode:d.data().code||d.id}));renderHome();if(!$('catalog-screen').hidden)renderCatalog()}));unsub.push(col('pengaturan').doc('beranda_pelanggan_home').onSnapshot(s=>{if(s.exists){const d=s.data();$('promo-text').textContent=d.runningText||d.infoText||'Belanja lebih hemat hari ini'}}))}
function openDetail(p){selected=p;detailQty=1;const src=photo(p);$('detail-image').innerHTML=src?`<img src="${esc(src)}" alt="${esc(p.nama)}">`:'🛒';$('detail-name').textContent=p.nama||'Produk';$('detail-price').textContent=money(p.hargaJual??p.harga);$('detail-stock').textContent=`Stok: ${p.stok??p.stock??'tersedia'}`;$('detail-desc').textContent=p.deskripsi||p.description||'Produk pilihan toko. Silakan hubungi admin jika membutuhkan informasi lebih lanjut.';$('detail-qty').textContent=detailQty;$('detail-sheet').hidden=false}
function closeDetail(){$('detail-sheet').hidden=true;selected=null}
function renderCart(){const c=cart();const total=c.reduce((a,x)=>a+x.harga*x.qty,0);$('cart-count').textContent=`${c.reduce((a,x)=>a+x.qty,0)} item`;$('cart-subtotal').textContent=money(total);$('cart-total').textContent=money(total);$('checkout-total').textContent=money(total);$('cart-items').innerHTML=c.length?c.map((x,i)=>`<div class="cart-item"><div class="cart-thumb">🛒</div><div class="cart-info"><b>${esc(x.nama)}</b><small>${money(x.harga)}</small><div class="cart-qty"><button data-cart="${i}" data-op="-">−</button><b>${x.qty}</b><button data-cart="${i}" data-op="+">+</button></div></div><strong>${money(x.harga*x.qty)}</strong></div>`).join(''):'<div class="empty cart-empty">Keranjang masih kosong 🛒</div>'}
function renderCheckout(){const c=cart(),total=c.reduce((a,x)=>a+x.harga*x.qty,0);$('checkout-summary').innerHTML=c.length?c.map(x=>`<div class="summary-row"><span>${esc(x.nama)} × ${x.qty}</span><b>${money(x.harga*x.qty)}</b></div>`).join(''):'<div class="empty">Tidak ada item.</div>';$('checkout-total').textContent=money(total)}
function renderProfile(){const name=localStorage.getItem('cust_name_v4')||'Pelanggan',phone=localStorage.getItem('cust_phone_v4')||'Belum masuk';$('profile-name').textContent=name;$('profile-phone').textContent=phone;$('profile-avatar').textContent=name.charAt(0).toUpperCase(); renderOrders([])}
function orderDate(o){const t=o?.waktuTimestamp;if(t?.toDate)return t.toDate();if(t?.seconds)return new Date(t.seconds*1000);const d=new Date(o?.waktu||0);return Number.isNaN(d.getTime())?new Date(0):d}
function orderStatusLabel(v){return ({baru:'Baru',diproses:'Diproses',selesai:'Selesai',batal:'Batal'})[v]||v||'Baru'}
function renderOrders(list){const box=$('customer-orders');if(!box)return;const sorted=list.slice().sort((a,b)=>orderDate(b)-orderDate(a));box.innerHTML=sorted.length?sorted.slice(0,12).map(o=>{const items=Array.isArray(o.items)?o.items:[];const qty=Number(o.qty||items.reduce((n,x)=>n+Number(x.qty||0),0));return `<div class="order-row"><div><b>#${esc(String(o.id||'Pesanan').slice(-8))}</b><small>${qty} item • ${esc(orderStatusLabel(o.status))}</small></div><span>${money(o.total)}</span><small>${esc(o.pembayaran||o.metode||'')} • ${esc(o.catatan||'')}</small></div>`}).join(''):'<div class="empty">Belum ada pesanan.</div>'}

function listenCustomerOrders(){if(orderUnsub)orderUnsub();const phone=localStorage.getItem('cust_phone_v4');if(!phone)return;try{orderUnsub=col('transaksi').where('customerPhone','==',phone).onSnapshot(s=>renderOrders(s.docs.map(d=>({...d.data(),id:d.id}))))}catch(e){console.warn(e)}}
function listenCustomerChat(){if(chatUnsub)chatUnsub();const phone=localStorage.getItem('cust_phone_v4');if(!phone)return;const root=col('chats').doc(phone);root.set({phone,customerNama:localStorage.getItem('cust_name_v4')||'Pelanggan',unreadCustomer:0},{merge:true}).catch(()=>{});const renderChat=s=>{const box=$('chat-messages');box.innerHTML=s.docs.map(d=>{const m=d.data();const mine=m.sender==='customer'||m.role==='customer'||m.pengirim==='customer';return `<div class=\"chat-bubble ${mine?'user':'admin'}\">${esc(m.text||m.message||m.pesan||'')}</div>`}).join('')||'<div class=\"chat-bubble admin\">Halo 👋 Ada yang bisa kami bantu?</div>';box.scrollTop=box.scrollHeight};chatUnsub=root.collection('messages').orderBy('waktuTimestamp','asc').onSnapshot(renderChat,()=>{chatUnsub=root.collection('messages').orderBy('createdAt','asc').onSnapshot(renderChat)})}
async function sendCustomerChat(text){const phone=localStorage.getItem('cust_phone_v4');if(!phone)throw Error('Silakan masuk terlebih dahulu.');const root=col('chats').doc(phone);await root.set({phone,customerNama:localStorage.getItem('cust_name_v4')||'Pelanggan',updatedAt:firebase.firestore.FieldValue.serverTimestamp(),lastMessage:'Customer: '+text,lastTimestamp:firebase.firestore.FieldValue.serverTimestamp(),unreadAdmin:firebase.firestore.FieldValue.increment(1)},{merge:true});await root.collection('messages').add({text,message:text,pesan:text,sender:'customer',role:'customer',pengirim:'customer',createdAt:firebase.firestore.FieldValue.serverTimestamp(),waktuTimestamp:firebase.firestore.FieldValue.serverTimestamp(),waktu:new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})})}
async function login(phone,pass){const s=await col('pelanggan').where('phone','==',phone).limit(1).get();if(s.empty)throw Error('Nomor WhatsApp belum terdaftar.');const d=s.docs[0].data();if(d.status==='pending'||d.disetujui===false)throw Error('Akun masih menunggu persetujuan Admin toko.');if(pass!==(d.password||'user'))throw Error('Sandi salah.');localStorage.setItem('cust_phone_v4',phone);localStorage.setItem('cust_name_v4',d.nama||'Pelanggan');window.KQV4.StoreContext.set({tokoId,user:d,role:'customer'});const next=loginReturn||'home';closeLogin();show(next);toast('Berhasil masuk. Selamat berbelanja 🛒')}
async function register(name,phone,address,pass){if(!name||!phone||!address||!pass)throw Error('Semua kolom wajib diisi.');const exists=await col('pelanggan').where('phone','==',phone).limit(1).get();if(!exists.empty)throw Error('Nomor WhatsApp sudah terdaftar.');await col('pelanggan').add({nama:name,phone,alamat:address,password:pass,status:'pending',catatan:[],savedRecipes:[],waktuDaftar:new Date().toLocaleString('id-ID')});toast('Pendaftaran berhasil. Menunggu persetujuan Admin.');document.querySelector('[data-mode="login"]').click()}
async function submitOrder(){const c=cart();if(!c.length)return toast('Keranjang masih kosong.');const phone=localStorage.getItem('cust_phone_v4');if(!phone)return openLogin('checkout');try{const fresh=[];for(const item of c){const productId=String(item.id||item.code||''); const snap=await col('produk').doc(productId).get();if(!snap.exists)throw Error(`Produk \"${item.nama}\" sudah tidak tersedia.`);const d=snap.data();const stock=Number(d.stok??d.stock??0);const price=Number(d.hargaJual??d.harga??0);if(stock<Number(item.qty))throw Error(`Stok \"${item.nama}\" tidak mencukupi.`);fresh.push({...item,id:productId,code:productId,harga:price,stokSaatPesan:stock})}const total=fresh.reduce((a,x)=>a+x.harga*x.qty,0);await col('transaksi').add({items:fresh.map(x=>({code:x.code,nama:x.nama,harga:x.harga,qty:x.qty})),total,pembayaran:payment,metode:payment.toLowerCase(),qty:fresh.reduce((a,x)=>a+Number(x.qty||0),0),catatan:$('order-note').value.trim(),customerPhone:phone,customerNama:localStorage.getItem('cust_name_v4')||'Pelanggan',status:'baru',statusPesanan:'Menunggu Diproses',waktu:new Date().toISOString(),waktuTimestamp:firebase.firestore.FieldValue.serverTimestamp(),stockAppliedAt:null});saveCart([]);$('order-note').value='';show('home');toast('Pesanan berhasil dibuat 🎉')}catch(e){toast('Pesanan belum tersimpan: '+e.message)}}
function init(){try{window.KQV4=window.KQV4||{};if(!window.KQV4.Firebase||typeof window.KQV4.Firebase.init!=='function')throw new Error('Firebase bootstrap belum dimuat.');window.KQV4.Firebase.init();window.KQV4.StoreContext.set({tokoId,role:'customer'})}catch(e){console.error(e);toast(e.message);return}greeting();show('home');if(!localStorage.getItem('cust_phone_v4'))openLogin('home');loadStore();listen();updateCartBadge()}
function updateCartBadge(){const n=cart().reduce((a,x)=>a+x.qty,0);const b=document.querySelector('[data-tab="cart"]');if(b)b.innerHTML=`🛒${n?`<i>${n}</i>`:''}<small>Keranjang</small>`}
$('search-input').addEventListener('input',e=>search(e.target.value));$('search-clear').onclick=()=>{$('search-input').value='';search('')};
$('catalog-back').onclick=()=>show('home');$('login-close').onclick=()=>closeLogin();$('login-backdrop').onclick=()=>closeLogin();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('login-screen').hidden)closeLogin()}); $('detail-minus').onclick=()=>{detailQty=Math.max(1,detailQty-1);$('detail-qty').textContent=detailQty};$('detail-plus').onclick=()=>{detailQty++;$('detail-qty').textContent=detailQty};$('detail-add').onclick=()=>{if(selected)add(selected,detailQty);closeDetail()};$('detail-chat').onclick=()=>{closeDetail();show('chat');$('chat-text').focus()};document.querySelectorAll('[data-close="detail"]').forEach(x=>x.onclick=closeDetail);
$('bottom-nav').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;show(b.dataset.tab)});
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)show(n.dataset.nav);const q=e.target.closest('[data-cart]');if(q){const c=cart(),i=+q.dataset.cart;if(q.dataset.op==='+')c[i].qty++;else c[i].qty=Math.max(1,c[i].qty-1);saveCart(c);renderCart();updateCartBadge()}});
$('cart-clear').onclick=()=>{saveCart([]);renderCart();updateCartBadge()};$('checkout-open').onclick=()=>cart().length?show('checkout'):toast('Keranjang masih kosong.');document.querySelectorAll('.pay').forEach(b=>b.onclick=()=>{document.querySelectorAll('.pay').forEach(x=>x.classList.remove('active'));b.classList.add('active');payment=b.dataset.pay});$('checkout-submit').onclick=submitOrder;
$('chat-form').onsubmit=async e=>{e.preventDefault();const t=$('chat-text').value.trim();if(!t)return;try{await sendCustomerChat(t);$('chat-text').value=''}catch(err){toast(err.message)}};
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>b.dataset.profile==='chat'?show('chat'):b.dataset.profile==='orders'?show('profile'):toast('Bagian ini siap dikembangkan pada modul berikutnya.'));$('logout-btn').onclick=()=>{if(chatUnsub)chatUnsub();if(orderUnsub)orderUnsub();localStorage.removeItem('cust_phone_v4');localStorage.removeItem('cust_name_v4');show('home');openLogin('home');toast('Anda sudah keluar.')};$('profile-btn').onclick=()=>localStorage.getItem('cust_phone_v4')?show('profile'):openLogin('profile');
document.querySelectorAll('.auth-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.auth-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const reg=b.dataset.mode==='register';$('login-fields').hidden=reg;$('register-fields').hidden=!reg});$('login-form').addEventListener('submit',async e=>{e.preventDefault();try{if(!$('login-fields').hidden)await login($('login-phone').value.trim(),$('login-pass').value);else await register($('reg-name').value.trim(),$('reg-phone').value.trim(),$('reg-address').value.trim(),$('reg-pass').value.trim())}catch(err){toast(err.message)}});
window.KQV4.ready(init);window.addEventListener('beforeunload',()=>unsub.forEach(f=>f&&f()));
})();
